package com.playjoy.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class AppVacation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_vacation.vacationid
     *
     * @mbg.generated
     */
    private String vacationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_vacation.apply_userid
     *
     * @mbg.generated
     */
    private String applyUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_vacation.apply_time
     *
     * @mbg.generated
     */
    private Date applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_vacation.vacation_begindate
     *
     * @mbg.generated
     */
    private Date vacationBegindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_vacation.vacation_enddate
     *
     * @mbg.generated
     */
    private Date vacationEnddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_vacation.vacation_days
     *
     * @mbg.generated
     */
    private Integer vacationDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_vacation.vacation_hours
     *
     * @mbg.generated
     */
    private BigDecimal vacationHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_vacation.vacation_type
     *
     * @mbg.generated
     */
    private String vacationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_vacation.vacation_reason
     *
     * @mbg.generated
     */
    private String vacationReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_vacation.audit_status
     *
     * @mbg.generated
     */
    private String auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_vacation.audit_userid
     *
     * @mbg.generated
     */
    private String auditUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_vacation.audit_time
     *
     * @mbg.generated
     */
    private Date auditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_vacation.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_vacation.vacationid
     *
     * @return the value of app_vacation.vacationid
     *
     * @mbg.generated
     */
    public String getVacationid() {
        return vacationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_vacation.vacationid
     *
     * @param vacationid the value for app_vacation.vacationid
     *
     * @mbg.generated
     */
    public void setVacationid(String vacationid) {
        this.vacationid = vacationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_vacation.apply_userid
     *
     * @return the value of app_vacation.apply_userid
     *
     * @mbg.generated
     */
    public String getApplyUserid() {
        return applyUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_vacation.apply_userid
     *
     * @param applyUserid the value for app_vacation.apply_userid
     *
     * @mbg.generated
     */
    public void setApplyUserid(String applyUserid) {
        this.applyUserid = applyUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_vacation.apply_time
     *
     * @return the value of app_vacation.apply_time
     *
     * @mbg.generated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_vacation.apply_time
     *
     * @param applyTime the value for app_vacation.apply_time
     *
     * @mbg.generated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_vacation.vacation_begindate
     *
     * @return the value of app_vacation.vacation_begindate
     *
     * @mbg.generated
     */
    public Date getVacationBegindate() {
        return vacationBegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_vacation.vacation_begindate
     *
     * @param vacationBegindate the value for app_vacation.vacation_begindate
     *
     * @mbg.generated
     */
    public void setVacationBegindate(Date vacationBegindate) {
        this.vacationBegindate = vacationBegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_vacation.vacation_enddate
     *
     * @return the value of app_vacation.vacation_enddate
     *
     * @mbg.generated
     */
    public Date getVacationEnddate() {
        return vacationEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_vacation.vacation_enddate
     *
     * @param vacationEnddate the value for app_vacation.vacation_enddate
     *
     * @mbg.generated
     */
    public void setVacationEnddate(Date vacationEnddate) {
        this.vacationEnddate = vacationEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_vacation.vacation_days
     *
     * @return the value of app_vacation.vacation_days
     *
     * @mbg.generated
     */
    public Integer getVacationDays() {
        return vacationDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_vacation.vacation_days
     *
     * @param vacationDays the value for app_vacation.vacation_days
     *
     * @mbg.generated
     */
    public void setVacationDays(Integer vacationDays) {
        this.vacationDays = vacationDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_vacation.vacation_hours
     *
     * @return the value of app_vacation.vacation_hours
     *
     * @mbg.generated
     */
    public BigDecimal getVacationHours() {
        return vacationHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_vacation.vacation_hours
     *
     * @param vacationHours the value for app_vacation.vacation_hours
     *
     * @mbg.generated
     */
    public void setVacationHours(BigDecimal vacationHours) {
        this.vacationHours = vacationHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_vacation.vacation_type
     *
     * @return the value of app_vacation.vacation_type
     *
     * @mbg.generated
     */
    public String getVacationType() {
        return vacationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_vacation.vacation_type
     *
     * @param vacationType the value for app_vacation.vacation_type
     *
     * @mbg.generated
     */
    public void setVacationType(String vacationType) {
        this.vacationType = vacationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_vacation.vacation_reason
     *
     * @return the value of app_vacation.vacation_reason
     *
     * @mbg.generated
     */
    public String getVacationReason() {
        return vacationReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_vacation.vacation_reason
     *
     * @param vacationReason the value for app_vacation.vacation_reason
     *
     * @mbg.generated
     */
    public void setVacationReason(String vacationReason) {
        this.vacationReason = vacationReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_vacation.audit_status
     *
     * @return the value of app_vacation.audit_status
     *
     * @mbg.generated
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_vacation.audit_status
     *
     * @param auditStatus the value for app_vacation.audit_status
     *
     * @mbg.generated
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_vacation.audit_userid
     *
     * @return the value of app_vacation.audit_userid
     *
     * @mbg.generated
     */
    public String getAuditUserid() {
        return auditUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_vacation.audit_userid
     *
     * @param auditUserid the value for app_vacation.audit_userid
     *
     * @mbg.generated
     */
    public void setAuditUserid(String auditUserid) {
        this.auditUserid = auditUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_vacation.audit_time
     *
     * @return the value of app_vacation.audit_time
     *
     * @mbg.generated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_vacation.audit_time
     *
     * @param auditTime the value for app_vacation.audit_time
     *
     * @mbg.generated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_vacation.updatetime
     *
     * @return the value of app_vacation.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_vacation.updatetime
     *
     * @param updatetime the value for app_vacation.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}