package com.playjoy.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AppVacationExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    public AppVacationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andVacationidIsNull() {
            addCriterion("vacationid is null");
            return (Criteria) this;
        }

        public Criteria andVacationidIsNotNull() {
            addCriterion("vacationid is not null");
            return (Criteria) this;
        }

        public Criteria andVacationidEqualTo(String value) {
            addCriterion("vacationid =", value, "vacationid");
            return (Criteria) this;
        }

        public Criteria andVacationidNotEqualTo(String value) {
            addCriterion("vacationid <>", value, "vacationid");
            return (Criteria) this;
        }

        public Criteria andVacationidGreaterThan(String value) {
            addCriterion("vacationid >", value, "vacationid");
            return (Criteria) this;
        }

        public Criteria andVacationidGreaterThanOrEqualTo(String value) {
            addCriterion("vacationid >=", value, "vacationid");
            return (Criteria) this;
        }

        public Criteria andVacationidLessThan(String value) {
            addCriterion("vacationid <", value, "vacationid");
            return (Criteria) this;
        }

        public Criteria andVacationidLessThanOrEqualTo(String value) {
            addCriterion("vacationid <=", value, "vacationid");
            return (Criteria) this;
        }

        public Criteria andVacationidLike(String value) {
            addCriterion("vacationid like", value, "vacationid");
            return (Criteria) this;
        }

        public Criteria andVacationidNotLike(String value) {
            addCriterion("vacationid not like", value, "vacationid");
            return (Criteria) this;
        }

        public Criteria andVacationidIn(List<String> values) {
            addCriterion("vacationid in", values, "vacationid");
            return (Criteria) this;
        }

        public Criteria andVacationidNotIn(List<String> values) {
            addCriterion("vacationid not in", values, "vacationid");
            return (Criteria) this;
        }

        public Criteria andVacationidBetween(String value1, String value2) {
            addCriterion("vacationid between", value1, value2, "vacationid");
            return (Criteria) this;
        }

        public Criteria andVacationidNotBetween(String value1, String value2) {
            addCriterion("vacationid not between", value1, value2, "vacationid");
            return (Criteria) this;
        }

        public Criteria andApplyUseridIsNull() {
            addCriterion("apply_userid is null");
            return (Criteria) this;
        }

        public Criteria andApplyUseridIsNotNull() {
            addCriterion("apply_userid is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUseridEqualTo(String value) {
            addCriterion("apply_userid =", value, "applyUserid");
            return (Criteria) this;
        }

        public Criteria andApplyUseridNotEqualTo(String value) {
            addCriterion("apply_userid <>", value, "applyUserid");
            return (Criteria) this;
        }

        public Criteria andApplyUseridGreaterThan(String value) {
            addCriterion("apply_userid >", value, "applyUserid");
            return (Criteria) this;
        }

        public Criteria andApplyUseridGreaterThanOrEqualTo(String value) {
            addCriterion("apply_userid >=", value, "applyUserid");
            return (Criteria) this;
        }

        public Criteria andApplyUseridLessThan(String value) {
            addCriterion("apply_userid <", value, "applyUserid");
            return (Criteria) this;
        }

        public Criteria andApplyUseridLessThanOrEqualTo(String value) {
            addCriterion("apply_userid <=", value, "applyUserid");
            return (Criteria) this;
        }

        public Criteria andApplyUseridLike(String value) {
            addCriterion("apply_userid like", value, "applyUserid");
            return (Criteria) this;
        }

        public Criteria andApplyUseridNotLike(String value) {
            addCriterion("apply_userid not like", value, "applyUserid");
            return (Criteria) this;
        }

        public Criteria andApplyUseridIn(List<String> values) {
            addCriterion("apply_userid in", values, "applyUserid");
            return (Criteria) this;
        }

        public Criteria andApplyUseridNotIn(List<String> values) {
            addCriterion("apply_userid not in", values, "applyUserid");
            return (Criteria) this;
        }

        public Criteria andApplyUseridBetween(String value1, String value2) {
            addCriterion("apply_userid between", value1, value2, "applyUserid");
            return (Criteria) this;
        }

        public Criteria andApplyUseridNotBetween(String value1, String value2) {
            addCriterion("apply_userid not between", value1, value2, "applyUserid");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIsNull() {
            addCriterion("apply_time is null");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIsNotNull() {
            addCriterion("apply_time is not null");
            return (Criteria) this;
        }

        public Criteria andApplyTimeEqualTo(Date value) {
            addCriterion("apply_time =", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotEqualTo(Date value) {
            addCriterion("apply_time <>", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeGreaterThan(Date value) {
            addCriterion("apply_time >", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("apply_time >=", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLessThan(Date value) {
            addCriterion("apply_time <", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLessThanOrEqualTo(Date value) {
            addCriterion("apply_time <=", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIn(List<Date> values) {
            addCriterion("apply_time in", values, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotIn(List<Date> values) {
            addCriterion("apply_time not in", values, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeBetween(Date value1, Date value2) {
            addCriterion("apply_time between", value1, value2, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotBetween(Date value1, Date value2) {
            addCriterion("apply_time not between", value1, value2, "applyTime");
            return (Criteria) this;
        }

        public Criteria andVacationBegindateIsNull() {
            addCriterion("vacation_begindate is null");
            return (Criteria) this;
        }

        public Criteria andVacationBegindateIsNotNull() {
            addCriterion("vacation_begindate is not null");
            return (Criteria) this;
        }

        public Criteria andVacationBegindateEqualTo(Date value) {
            addCriterionForJDBCDate("vacation_begindate =", value, "vacationBegindate");
            return (Criteria) this;
        }

        public Criteria andVacationBegindateNotEqualTo(Date value) {
            addCriterionForJDBCDate("vacation_begindate <>", value, "vacationBegindate");
            return (Criteria) this;
        }

        public Criteria andVacationBegindateGreaterThan(Date value) {
            addCriterionForJDBCDate("vacation_begindate >", value, "vacationBegindate");
            return (Criteria) this;
        }

        public Criteria andVacationBegindateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("vacation_begindate >=", value, "vacationBegindate");
            return (Criteria) this;
        }

        public Criteria andVacationBegindateLessThan(Date value) {
            addCriterionForJDBCDate("vacation_begindate <", value, "vacationBegindate");
            return (Criteria) this;
        }

        public Criteria andVacationBegindateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("vacation_begindate <=", value, "vacationBegindate");
            return (Criteria) this;
        }

        public Criteria andVacationBegindateIn(List<Date> values) {
            addCriterionForJDBCDate("vacation_begindate in", values, "vacationBegindate");
            return (Criteria) this;
        }

        public Criteria andVacationBegindateNotIn(List<Date> values) {
            addCriterionForJDBCDate("vacation_begindate not in", values, "vacationBegindate");
            return (Criteria) this;
        }

        public Criteria andVacationBegindateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("vacation_begindate between", value1, value2, "vacationBegindate");
            return (Criteria) this;
        }

        public Criteria andVacationBegindateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("vacation_begindate not between", value1, value2, "vacationBegindate");
            return (Criteria) this;
        }

        public Criteria andVacationEnddateIsNull() {
            addCriterion("vacation_enddate is null");
            return (Criteria) this;
        }

        public Criteria andVacationEnddateIsNotNull() {
            addCriterion("vacation_enddate is not null");
            return (Criteria) this;
        }

        public Criteria andVacationEnddateEqualTo(Date value) {
            addCriterionForJDBCDate("vacation_enddate =", value, "vacationEnddate");
            return (Criteria) this;
        }

        public Criteria andVacationEnddateNotEqualTo(Date value) {
            addCriterionForJDBCDate("vacation_enddate <>", value, "vacationEnddate");
            return (Criteria) this;
        }

        public Criteria andVacationEnddateGreaterThan(Date value) {
            addCriterionForJDBCDate("vacation_enddate >", value, "vacationEnddate");
            return (Criteria) this;
        }

        public Criteria andVacationEnddateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("vacation_enddate >=", value, "vacationEnddate");
            return (Criteria) this;
        }

        public Criteria andVacationEnddateLessThan(Date value) {
            addCriterionForJDBCDate("vacation_enddate <", value, "vacationEnddate");
            return (Criteria) this;
        }

        public Criteria andVacationEnddateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("vacation_enddate <=", value, "vacationEnddate");
            return (Criteria) this;
        }

        public Criteria andVacationEnddateIn(List<Date> values) {
            addCriterionForJDBCDate("vacation_enddate in", values, "vacationEnddate");
            return (Criteria) this;
        }

        public Criteria andVacationEnddateNotIn(List<Date> values) {
            addCriterionForJDBCDate("vacation_enddate not in", values, "vacationEnddate");
            return (Criteria) this;
        }

        public Criteria andVacationEnddateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("vacation_enddate between", value1, value2, "vacationEnddate");
            return (Criteria) this;
        }

        public Criteria andVacationEnddateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("vacation_enddate not between", value1, value2, "vacationEnddate");
            return (Criteria) this;
        }

        public Criteria andVacationDaysIsNull() {
            addCriterion("vacation_days is null");
            return (Criteria) this;
        }

        public Criteria andVacationDaysIsNotNull() {
            addCriterion("vacation_days is not null");
            return (Criteria) this;
        }

        public Criteria andVacationDaysEqualTo(Integer value) {
            addCriterion("vacation_days =", value, "vacationDays");
            return (Criteria) this;
        }

        public Criteria andVacationDaysNotEqualTo(Integer value) {
            addCriterion("vacation_days <>", value, "vacationDays");
            return (Criteria) this;
        }

        public Criteria andVacationDaysGreaterThan(Integer value) {
            addCriterion("vacation_days >", value, "vacationDays");
            return (Criteria) this;
        }

        public Criteria andVacationDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("vacation_days >=", value, "vacationDays");
            return (Criteria) this;
        }

        public Criteria andVacationDaysLessThan(Integer value) {
            addCriterion("vacation_days <", value, "vacationDays");
            return (Criteria) this;
        }

        public Criteria andVacationDaysLessThanOrEqualTo(Integer value) {
            addCriterion("vacation_days <=", value, "vacationDays");
            return (Criteria) this;
        }

        public Criteria andVacationDaysIn(List<Integer> values) {
            addCriterion("vacation_days in", values, "vacationDays");
            return (Criteria) this;
        }

        public Criteria andVacationDaysNotIn(List<Integer> values) {
            addCriterion("vacation_days not in", values, "vacationDays");
            return (Criteria) this;
        }

        public Criteria andVacationDaysBetween(Integer value1, Integer value2) {
            addCriterion("vacation_days between", value1, value2, "vacationDays");
            return (Criteria) this;
        }

        public Criteria andVacationDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("vacation_days not between", value1, value2, "vacationDays");
            return (Criteria) this;
        }

        public Criteria andVacationHoursIsNull() {
            addCriterion("vacation_hours is null");
            return (Criteria) this;
        }

        public Criteria andVacationHoursIsNotNull() {
            addCriterion("vacation_hours is not null");
            return (Criteria) this;
        }

        public Criteria andVacationHoursEqualTo(BigDecimal value) {
            addCriterion("vacation_hours =", value, "vacationHours");
            return (Criteria) this;
        }

        public Criteria andVacationHoursNotEqualTo(BigDecimal value) {
            addCriterion("vacation_hours <>", value, "vacationHours");
            return (Criteria) this;
        }

        public Criteria andVacationHoursGreaterThan(BigDecimal value) {
            addCriterion("vacation_hours >", value, "vacationHours");
            return (Criteria) this;
        }

        public Criteria andVacationHoursGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("vacation_hours >=", value, "vacationHours");
            return (Criteria) this;
        }

        public Criteria andVacationHoursLessThan(BigDecimal value) {
            addCriterion("vacation_hours <", value, "vacationHours");
            return (Criteria) this;
        }

        public Criteria andVacationHoursLessThanOrEqualTo(BigDecimal value) {
            addCriterion("vacation_hours <=", value, "vacationHours");
            return (Criteria) this;
        }

        public Criteria andVacationHoursIn(List<BigDecimal> values) {
            addCriterion("vacation_hours in", values, "vacationHours");
            return (Criteria) this;
        }

        public Criteria andVacationHoursNotIn(List<BigDecimal> values) {
            addCriterion("vacation_hours not in", values, "vacationHours");
            return (Criteria) this;
        }

        public Criteria andVacationHoursBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("vacation_hours between", value1, value2, "vacationHours");
            return (Criteria) this;
        }

        public Criteria andVacationHoursNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("vacation_hours not between", value1, value2, "vacationHours");
            return (Criteria) this;
        }

        public Criteria andVacationTypeIsNull() {
            addCriterion("vacation_type is null");
            return (Criteria) this;
        }

        public Criteria andVacationTypeIsNotNull() {
            addCriterion("vacation_type is not null");
            return (Criteria) this;
        }

        public Criteria andVacationTypeEqualTo(String value) {
            addCriterion("vacation_type =", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeNotEqualTo(String value) {
            addCriterion("vacation_type <>", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeGreaterThan(String value) {
            addCriterion("vacation_type >", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("vacation_type >=", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeLessThan(String value) {
            addCriterion("vacation_type <", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeLessThanOrEqualTo(String value) {
            addCriterion("vacation_type <=", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeLike(String value) {
            addCriterion("vacation_type like", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeNotLike(String value) {
            addCriterion("vacation_type not like", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeIn(List<String> values) {
            addCriterion("vacation_type in", values, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeNotIn(List<String> values) {
            addCriterion("vacation_type not in", values, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeBetween(String value1, String value2) {
            addCriterion("vacation_type between", value1, value2, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeNotBetween(String value1, String value2) {
            addCriterion("vacation_type not between", value1, value2, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationReasonIsNull() {
            addCriterion("vacation_reason is null");
            return (Criteria) this;
        }

        public Criteria andVacationReasonIsNotNull() {
            addCriterion("vacation_reason is not null");
            return (Criteria) this;
        }

        public Criteria andVacationReasonEqualTo(String value) {
            addCriterion("vacation_reason =", value, "vacationReason");
            return (Criteria) this;
        }

        public Criteria andVacationReasonNotEqualTo(String value) {
            addCriterion("vacation_reason <>", value, "vacationReason");
            return (Criteria) this;
        }

        public Criteria andVacationReasonGreaterThan(String value) {
            addCriterion("vacation_reason >", value, "vacationReason");
            return (Criteria) this;
        }

        public Criteria andVacationReasonGreaterThanOrEqualTo(String value) {
            addCriterion("vacation_reason >=", value, "vacationReason");
            return (Criteria) this;
        }

        public Criteria andVacationReasonLessThan(String value) {
            addCriterion("vacation_reason <", value, "vacationReason");
            return (Criteria) this;
        }

        public Criteria andVacationReasonLessThanOrEqualTo(String value) {
            addCriterion("vacation_reason <=", value, "vacationReason");
            return (Criteria) this;
        }

        public Criteria andVacationReasonLike(String value) {
            addCriterion("vacation_reason like", value, "vacationReason");
            return (Criteria) this;
        }

        public Criteria andVacationReasonNotLike(String value) {
            addCriterion("vacation_reason not like", value, "vacationReason");
            return (Criteria) this;
        }

        public Criteria andVacationReasonIn(List<String> values) {
            addCriterion("vacation_reason in", values, "vacationReason");
            return (Criteria) this;
        }

        public Criteria andVacationReasonNotIn(List<String> values) {
            addCriterion("vacation_reason not in", values, "vacationReason");
            return (Criteria) this;
        }

        public Criteria andVacationReasonBetween(String value1, String value2) {
            addCriterion("vacation_reason between", value1, value2, "vacationReason");
            return (Criteria) this;
        }

        public Criteria andVacationReasonNotBetween(String value1, String value2) {
            addCriterion("vacation_reason not between", value1, value2, "vacationReason");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("audit_status is null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("audit_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusEqualTo(String value) {
            addCriterion("audit_status =", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotEqualTo(String value) {
            addCriterion("audit_status <>", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThan(String value) {
            addCriterion("audit_status >", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(String value) {
            addCriterion("audit_status >=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThan(String value) {
            addCriterion("audit_status <", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(String value) {
            addCriterion("audit_status <=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLike(String value) {
            addCriterion("audit_status like", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotLike(String value) {
            addCriterion("audit_status not like", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIn(List<String> values) {
            addCriterion("audit_status in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotIn(List<String> values) {
            addCriterion("audit_status not in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusBetween(String value1, String value2) {
            addCriterion("audit_status between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotBetween(String value1, String value2) {
            addCriterion("audit_status not between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditUseridIsNull() {
            addCriterion("audit_userid is null");
            return (Criteria) this;
        }

        public Criteria andAuditUseridIsNotNull() {
            addCriterion("audit_userid is not null");
            return (Criteria) this;
        }

        public Criteria andAuditUseridEqualTo(String value) {
            addCriterion("audit_userid =", value, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridNotEqualTo(String value) {
            addCriterion("audit_userid <>", value, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridGreaterThan(String value) {
            addCriterion("audit_userid >", value, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridGreaterThanOrEqualTo(String value) {
            addCriterion("audit_userid >=", value, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridLessThan(String value) {
            addCriterion("audit_userid <", value, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridLessThanOrEqualTo(String value) {
            addCriterion("audit_userid <=", value, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridLike(String value) {
            addCriterion("audit_userid like", value, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridNotLike(String value) {
            addCriterion("audit_userid not like", value, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridIn(List<String> values) {
            addCriterion("audit_userid in", values, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridNotIn(List<String> values) {
            addCriterion("audit_userid not in", values, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridBetween(String value1, String value2) {
            addCriterion("audit_userid between", value1, value2, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridNotBetween(String value1, String value2) {
            addCriterion("audit_userid not between", value1, value2, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("audit_time is null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("audit_time is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeEqualTo(Date value) {
            addCriterion("audit_time =", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotEqualTo(Date value) {
            addCriterion("audit_time <>", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThan(Date value) {
            addCriterion("audit_time >", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("audit_time >=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThan(Date value) {
            addCriterion("audit_time <", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(Date value) {
            addCriterion("audit_time <=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIn(List<Date> values) {
            addCriterion("audit_time in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotIn(List<Date> values) {
            addCriterion("audit_time not in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeBetween(Date value1, Date value2) {
            addCriterion("audit_time between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotBetween(Date value1, Date value2) {
            addCriterion("audit_time not between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_vacation
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}