package com.playjoy.entity;

import java.io.Serializable;
import java.util.Date;

public class DataSign implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_sign.signid
     *
     * @mbg.generated
     */
    private String signid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_sign.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_sign.sign_date
     *
     * @mbg.generated
     */
    private Date signDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_sign.startup_time
     *
     * @mbg.generated
     */
    private Date startupTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_sign.startup_posid
     *
     * @mbg.generated
     */
    private String startupPosid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_sign.off_time
     *
     * @mbg.generated
     */
    private Date offTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_sign.off_posid
     *
     * @mbg.generated
     */
    private String offPosid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_sign.deleteflag
     *
     * @mbg.generated
     */
    private Boolean deleteflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_sign.signid
     *
     * @return the value of data_sign.signid
     *
     * @mbg.generated
     */
    public String getSignid() {
        return signid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_sign.signid
     *
     * @param signid the value for data_sign.signid
     *
     * @mbg.generated
     */
    public void setSignid(String signid) {
        this.signid = signid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_sign.userid
     *
     * @return the value of data_sign.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_sign.userid
     *
     * @param userid the value for data_sign.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_sign.sign_date
     *
     * @return the value of data_sign.sign_date
     *
     * @mbg.generated
     */
    public Date getSignDate() {
        return signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_sign.sign_date
     *
     * @param signDate the value for data_sign.sign_date
     *
     * @mbg.generated
     */
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_sign.startup_time
     *
     * @return the value of data_sign.startup_time
     *
     * @mbg.generated
     */
    public Date getStartupTime() {
        return startupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_sign.startup_time
     *
     * @param startupTime the value for data_sign.startup_time
     *
     * @mbg.generated
     */
    public void setStartupTime(Date startupTime) {
        this.startupTime = startupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_sign.startup_posid
     *
     * @return the value of data_sign.startup_posid
     *
     * @mbg.generated
     */
    public String getStartupPosid() {
        return startupPosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_sign.startup_posid
     *
     * @param startupPosid the value for data_sign.startup_posid
     *
     * @mbg.generated
     */
    public void setStartupPosid(String startupPosid) {
        this.startupPosid = startupPosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_sign.off_time
     *
     * @return the value of data_sign.off_time
     *
     * @mbg.generated
     */
    public Date getOffTime() {
        return offTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_sign.off_time
     *
     * @param offTime the value for data_sign.off_time
     *
     * @mbg.generated
     */
    public void setOffTime(Date offTime) {
        this.offTime = offTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_sign.off_posid
     *
     * @return the value of data_sign.off_posid
     *
     * @mbg.generated
     */
    public String getOffPosid() {
        return offPosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_sign.off_posid
     *
     * @param offPosid the value for data_sign.off_posid
     *
     * @mbg.generated
     */
    public void setOffPosid(String offPosid) {
        this.offPosid = offPosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_sign.deleteflag
     *
     * @return the value of data_sign.deleteflag
     *
     * @mbg.generated
     */
    public Boolean getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_sign.deleteflag
     *
     * @param deleteflag the value for data_sign.deleteflag
     *
     * @mbg.generated
     */
    public void setDeleteflag(Boolean deleteflag) {
        this.deleteflag = deleteflag;
    }
}