package com.playjoy.mapper;

import com.playjoy.entity.AppVacation;
import com.playjoy.entity.AppVacationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppVacationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    long countByExample(AppVacationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    int deleteByExample(AppVacationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String vacationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    int insert(AppVacation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    int insertSelective(AppVacation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    List<AppVacation> selectByExample(AppVacationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    AppVacation selectByPrimaryKey(String vacationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AppVacation record, @Param("example") AppVacationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AppVacation record, @Param("example") AppVacationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
        int updateByPrimaryKeySelective(AppVacation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vacation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppVacation record);
}